# Build image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Inventario.Frontend/Inventario.Frontend.csproj", "Inventario.Frontend/"]
RUN dotnet restore --disable-parallel "Inventario.Frontend/Inventario.Frontend.csproj"

COPY . .
WORKDIR "/src/Inventario.Frontend"
RUN dotnet build "Inventario.Frontend.csproj" -c Release -o /app/build

# Publish image
FROM build AS publish
RUN dotnet publish "Inventario.Frontend.csproj" -c Release -o /app/publish

# Final image (runtime only)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Inventario.Frontend.dll"]

ENV ASPNETCORE_URLS=http://+:5001
